import type { ConsoleDomainFixture } from "./domain";

const timestamp = "2026-08-21T10:42:00+08:00";

/**
 * Read-only, in-memory fixtures for the future Console domain layer.
 * Existing and future Console pages consume this through repositories.
 */
export const consoleDomainFixture: ConsoleDomainFixture = {
  tools: [
    {
      id: "tool.remove-bg",
      slug: "remove-bg",
      name: "智能抠图",
      category: "image",
      version: "1.0.0",
      status: "active",
      executionMode: "browser",
      capabilities: ["background-removal", "transparent-png-export"],
      createdAt: "2026-08-01T09:00:00+08:00",
      updatedAt: timestamp,
    },
    {
      id: "tool.image-compress",
      slug: "image-compress",
      name: "图片压缩",
      category: "image",
      version: "1.0.0",
      status: "active",
      executionMode: "browser",
      capabilities: ["image-compression", "format-export"],
      createdAt: "2026-08-02T09:00:00+08:00",
      updatedAt: timestamp,
    },
    {
      id: "tool.pdf-to-images",
      slug: "pdf-to-images",
      name: "PDF 转图片",
      category: "document",
      version: "1.0.0",
      status: "active",
      executionMode: "browser",
      capabilities: ["pdf-rendering", "page-export"],
      createdAt: "2026-08-03T09:00:00+08:00",
      updatedAt: timestamp,
    },
  ],
  tasks: [
    {
      id: "task.remove-bg.20260821.1042",
      toolId: "tool.remove-bg",
      status: "succeeded",
      submittedAt: "2026-08-21T10:42:00+08:00",
      startedAt: "2026-08-21T10:42:01+08:00",
      completedAt: "2026-08-21T10:42:03+08:00",
      runtimeNodeId: "node.mac-mini.production",
      modelRevisionId: "model.fangcun-cutout.1.2",
      latestAttemptId: "attempt.remove-bg.20260821.1042.1",
      inputSummary: "1 image · 2048 × 2048 · PNG",
      outputSummary: "1 image · transparent PNG",
      metricSummary: { durationMs: 1820, outputCount: 1 },
    },
  ],
  taskArtifacts: [
    {
      id: "artifact.remove-bg.20260821.1042.input",
      taskId: "task.remove-bg.20260821.1042",
      role: "input",
      kind: "image",
      name: "product-glass-01.png",
      mediaType: "image/png",
      bytes: 2480000,
      reference: "local://task/remove-bg/20260821-1042/input",
      metadata: { width: 2048, height: 2048, hasAlpha: false },
      createdAt: timestamp,
    },
    {
      id: "artifact.remove-bg.20260821.1042.output",
      taskId: "task.remove-bg.20260821.1042",
      role: "output",
      kind: "image",
      name: "product-glass-01-cutout.png",
      mediaType: "image/png",
      bytes: 1910000,
      reference: "local://task/remove-bg/20260821-1042/output",
      metadata: { width: 2048, height: 2048, hasAlpha: true },
      createdAt: "2026-08-21T10:42:03+08:00",
    },
  ],
  taskAttempts: [
    {
      id: "attempt.remove-bg.20260821.1042.1",
      taskId: "task.remove-bg.20260821.1042",
      number: 1,
      status: "succeeded",
      runtimeNodeId: "node.mac-mini.production",
      modelRevisionId: "model.fangcun-cutout.1.2",
      startedAt: "2026-08-21T10:42:01+08:00",
      completedAt: "2026-08-21T10:42:03+08:00",
      durationMs: 1820,
      metrics: { inputPixels: 4194304, outputCount: 1 },
    },
  ],
  runtimeNodes: [
    {
      id: "node.mac-mini.production",
      name: "Mac mini production primary",
      environment: "production",
      role: "primary",
      hardware: "Apple Silicon · 32 GB",
      software: "Fangcun Runtime 2026.08",
      capabilities: ["image-processing", "local-inference"],
      health: "healthy",
      lastVerifiedAt: "2026-08-21T15:24:00+08:00",
    },
    {
      id: "node.r7000p.fallback",
      name: "R7000P fallback",
      environment: "production",
      role: "fallback",
      hardware: "RTX GPU · 16 GB",
      software: "Fangcun Runtime 2026.08",
      capabilities: ["image-processing", "gpu-inference"],
      health: "unknown",
      lastVerifiedAt: "2026-08-21T15:08:00+08:00",
    },
  ],
  serviceInstances: [
    {
      id: "service.production-api",
      type: "api",
      name: "Production API",
      runtimeNodeId: "node.mac-mini.production",
      endpoint: "api.fangcun.example",
      version: "2026.08.3",
      health: "healthy",
      dependencyIds: ["node.mac-mini.production"],
      lastVerifiedAt: "2026-08-21T15:24:00+08:00",
    },
    {
      id: "service.pages-deployment",
      type: "deployment",
      name: "Pages Deployment",
      endpoint: "app.fangcun.example",
      version: "rel_2026_08_21_01",
      health: "healthy",
      dependencyIds: ["service.production-api"],
      lastVerifiedAt: "2026-08-21T15:24:00+08:00",
    },
  ],
  modelRevisions: [
    {
      id: "model.fangcun-cutout.1.2",
      modelId: "fangcun-cutout",
      revision: "1.2",
      source: "local package",
      supportedToolIds: ["tool.remove-bg"],
      supportedRuntimeNodeIds: ["node.mac-mini.production", "node.r7000p.fallback"],
      qualityBaseline: "transparent-edge regression baseline",
      performanceProfile: "P95 3.12s at 2048 × 2048",
      status: "active",
    },
  ],
  datasets: [
    {
      id: "dataset.cutout-regression.v1",
      name: "Cutout Regression Set",
      version: "v1",
      sampleCount: 128,
      purpose: "Transparent-edge regression validation",
      status: "active",
      updatedAt: "2026-08-21T09:31:00+08:00",
    },
    {
      id: "dataset.image-utility-smoke.v1",
      name: "Image Utility Smoke Set",
      version: "v1",
      sampleCount: 36,
      purpose: "Cross-tool browser processing smoke checks",
      status: "candidate",
      updatedAt: "2026-08-20T16:12:00+08:00",
    },
  ],
  qualityRuns: [
    {
      id: "quality.cutout.20260821.003",
      datasetId: "dataset.cutout-regression.v1",
      toolId: "tool.remove-bg",
      modelRevisionId: "model.fangcun-cutout.1.2",
      status: "passed",
      totalCases: 128,
      passedCases: 128,
      metrics: { p95Ms: 1840, edgeScore: 0.98 },
      baseline: "transparent-edge regression baseline",
      completedAt: "2026-08-21T09:31:00+08:00",
    },
  ],
  events: [
    {
      id: "event.task.remove-bg.20260821.1042.succeeded",
      occurredAt: "2026-08-21T10:42:03+08:00",
      severity: "info",
      domain: "task",
      type: "task.succeeded",
      subjectType: "task",
      subjectId: "task.remove-bg.20260821.1042",
      toolId: "tool.remove-bg",
      taskId: "task.remove-bg.20260821.1042",
      taskAttemptId: "attempt.remove-bg.20260821.1042.1",
      runtimeNodeId: "node.mac-mini.production",
      correlationId: "task.remove-bg.20260821.1042",
      message: "Background removal completed with one transparent PNG output.",
      metadata: { durationMs: 1820, outputCount: 1 },
    },
    {
      id: "event.runtime.mac-mini.verified",
      occurredAt: "2026-08-21T15:24:00+08:00",
      severity: "info",
      domain: "runtime",
      type: "runtime.health_verified",
      subjectType: "runtime_node",
      subjectId: "node.mac-mini.production",
      runtimeNodeId: "node.mac-mini.production",
      message: "Mac mini production primary health verification completed.",
      metadata: { healthyServices: 4 },
    },
  ],
};
